export const constants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    POPULATION_FETCH:'POPULATION_FETCH',
    LITERACY_FETCH:'LITERACY_FETCH'
}